version: '3'

services:
  
  api:
    build:
      context: ./whatsapp-backend
      dockerfile: Dockerfile
    restart: always
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI='mongodb+srv://Ravi1234:password@cluster0.4skmkwf.mongodb.net/?retryWrites=true&w=majority'
    
  client:
    build:
      context: ./whatsapp-frontend
      dockerfile: Dockerfile
    restart: always
    container_name: client
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL='http://api:5000'
    depends_on:
      - api